"""Add wizard fields to PIPRecord; make TimelineEvent.pip_record_id nullable

Revision ID: 01f5e8bdb1f1
Revises: 204f59debcc0
Create Date: 2025-08-09 22:09:04.222783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f5e8bdb1f1'
down_revision = '204f59debcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
