"""Add Employee Relations documents

Revision ID: 2e2256b4de39
Revises: d7b51d361fcf
Create Date: 2026-03-23 14:40:33.399124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2256b4de39'
down_revision = 'd7b51d361fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_relations_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('finalised_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_documents_case_id'), 'employee_relations_documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_documents_document_type'), 'employee_relations_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_employee_relations_documents_status'), 'employee_relations_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_relations_documents_status'), table_name='employee_relations_documents')
    op.drop_index(op.f('ix_employee_relations_documents_document_type'), table_name='employee_relations_documents')
    op.drop_index(op.f('ix_employee_relations_documents_case_id'), table_name='employee_relations_documents')
    op.drop_table('employee_relations_documents')
    # ### end Alembic commands ###
