"""Add employee lifecycle fields

Revision ID: 4171ca098da6
Revises: 25832f139f7d
Create Date: 2026-03-24 11:44:52.439782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4171ca098da6'
down_revision = '25832f139f7d'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'employee',
        sa.Column('employment_status', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('is_leaver', sa.Boolean(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('leaving_date', sa.Date(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('leaving_reason_category', sa.String(length=100), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('leaving_reason_detail', sa.Text(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('leaving_notes', sa.Text(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('marked_as_leaver_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('marked_as_leaver_by', sa.String(length=120), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('reactivated_at', sa.DateTime(), nullable=True)
    )
    op.add_column(
        'employee',
        sa.Column('reactivated_by', sa.String(length=120), nullable=True)
    )

    op.execute("UPDATE employee SET employment_status = 'Active' WHERE employment_status IS NULL")
    op.execute("UPDATE employee SET is_leaver = 0 WHERE is_leaver IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'reactivated_by')
    op.drop_column('employee', 'reactivated_at')
    op.drop_column('employee', 'marked_as_leaver_by')
    op.drop_column('employee', 'marked_as_leaver_at')
    op.drop_column('employee', 'leaving_notes')
    op.drop_column('employee', 'leaving_reason_detail')
    op.drop_column('employee', 'leaving_reason_category')
    op.drop_column('employee', 'leaving_date')
    op.drop_column('employee', 'is_leaver')
    op.drop_column('employee', 'employment_status')
    # ### end Alembic commands ###
