"""add DocumentFile

Revision ID: 4305a2222270
Revises: 601fda3cb1c4
Create Date: 2025-09-04 22:05:34.348411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4305a2222270'
down_revision = '601fda3cb1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pip_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('docx_path', sa.String(length=255), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('html_snapshot', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['pip_id'], ['pip_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pip_id', 'doc_type', 'version', name='uq_pip_doctype_version')
    )
    op.create_index(op.f('ix_document_files_pip_id'), 'document_files', ['pip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_files_pip_id'), table_name='document_files')
    op.drop_table('document_files')
    # ### end Alembic commands ###
