"""Remove action_plan from PIPRecord

Revision ID: 497f3e2cc55e
Revises: e52626e7f497
Create Date: 2025-07-20 23:04:15.903581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497f3e2cc55e'
down_revision = 'e52626e7f497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.drop_column('action_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_plan', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
