"""Add employee relations policy texts

Revision ID: 4c7c0a0e3fd5
Revises: 2e2256b4de39
Create Date: 2026-03-23 16:07:00.852951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c0a0e3fd5'
down_revision = '2e2256b4de39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_relations_policy_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_attachment_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.ForeignKeyConstraint(['source_attachment_id'], ['employee_relations_attachments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_policy_texts_case_id'), 'employee_relations_policy_texts', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_policy_texts_source_attachment_id'), 'employee_relations_policy_texts', ['source_attachment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_relations_policy_texts_source_attachment_id'), table_name='employee_relations_policy_texts')
    op.drop_index(op.f('ix_employee_relations_policy_texts_case_id'), table_name='employee_relations_policy_texts')
    op.drop_table('employee_relations_policy_texts')
    # ### end Alembic commands ###
