"""Add probation models

Revision ID: 55fbcf0f3628
Revises: e6ba10759c18
Create Date: 2025-07-29 15:01:02.550678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fbcf0f3628'
down_revision = 'e6ba10759c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probation_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('probation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['probation_id'], ['probation_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probation_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('probation_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewer', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('concerns_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['probation_id'], ['probation_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probation_review')
    op.drop_table('probation_plan')
    op.drop_table('probation_record')
    # ### end Alembic commands ###
