"""add AI fields to PIPRecord and importjob json fix

Revision ID: 601fda3cb1c4
Revises: b06f33dbd287
Create Date: 2025-08-28 12:56:19.937528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '601fda3cb1c4'
down_revision = 'b06f33dbd287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pip_record', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('pip_record', sa.Column('ai_action_suggestions', sqlite.JSON(), nullable=True))
    op.add_column('pip_record', sa.Column('ai_next_up', sqlite.JSON(), nullable=True))
    op.add_column('pip_record', sa.Column('ai_actions_accepted', sqlite.JSON(), nullable=True))
    op.add_column('pip_record', sa.Column('outcome_status', sa.String(length=50), nullable=True))
    op.add_column('pip_record', sa.Column('outcome_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pip_record', 'outcome_notes')
    op.drop_column('pip_record', 'outcome_status')
    op.drop_column('pip_record', 'ai_actions_accepted')
    op.drop_column('pip_record', 'ai_next_up')
    op.drop_column('pip_record', 'ai_action_suggestions')
    op.drop_column('pip_record', 'ai_summary')
    # ### end Alembic commands ###
