"""empty message

Revision ID: 879c66dddb8f
Revises: 4305a2222270
Create Date: 2025-09-04 23:11:16.048124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879c66dddb8f'
down_revision = '4305a2222270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pip_record', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pip_record', 'user', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pip_record', type_='foreignkey')
    op.drop_column('pip_record', 'assigned_to')
    # ### end Alembic commands ###
