"""Add employee relations ai advice

Revision ID: 8d9e91746936
Revises: 4c7c0a0e3fd5
Create Date: 2026-03-23 22:14:00.361574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9e91746936'
down_revision = '4c7c0a0e3fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
