"""Initial migration with ai_advice

Revision ID: 9658cd988851
Revises: a57d87fb230f
Create Date: 2025-07-21 15:01:50.760159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9658cd988851'
down_revision = 'a57d87fb230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
