"""Add actions and timeline_events to PIPRecord

Revision ID: 9675f85d84a3
Revises: 497f3e2cc55e
Create Date: 2025-07-20 23:56:12.047258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9675f85d84a3'
down_revision = '497f3e2cc55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
