"""Add last_updated to PIPRecord

Revision ID: a528a7276aa9
Revises: f2e144063f63
Create Date: 2025-07-20 22:10:51.438085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a528a7276aa9'
down_revision = 'f2e144063f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
