"""add DraftProbation table

Revision ID: b06f33dbd287
Revises: c66bca5622b9
Create Date: 2025-08-24 20:42:21.384809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06f33dbd287'
down_revision = 'c66bca5622b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_probation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_probation_user_id'), 'draft_probation', ['user_id'], unique=False)
    op.create_index('ix_probation_draft_user_active', 'draft_probation', ['user_id', 'is_dismissed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_probation_draft_user_active', table_name='draft_probation')
    op.drop_index(op.f('ix_draft_probation_user_id'), table_name='draft_probation')
    op.drop_table('draft_probation')
    # ### end Alembic commands ###
