"""Add Employee Relations meetings and attachments

Revision ID: d7b51d361fcf
Revises: f52141811ccb
Create Date: 2026-03-23 13:04:35.027940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b51d361fcf'
down_revision = 'f52141811ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_relations_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('document_category', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_attachments_case_id'), 'employee_relations_attachments', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_attachments_uploaded_at'), 'employee_relations_attachments', ['uploaded_at'], unique=False)
    op.create_table('employee_relations_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=100), nullable=False),
    sa.Column('meeting_datetime', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('adjournment_notes', sa.Text(), nullable=True),
    sa.Column('outcome_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_meetings_case_id'), 'employee_relations_meetings', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_meetings_meeting_datetime'), 'employee_relations_meetings', ['meeting_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_relations_meetings_meeting_datetime'), table_name='employee_relations_meetings')
    op.drop_index(op.f('ix_employee_relations_meetings_case_id'), table_name='employee_relations_meetings')
    op.drop_table('employee_relations_meetings')
    op.drop_index(op.f('ix_employee_relations_attachments_uploaded_at'), table_name='employee_relations_attachments')
    op.drop_index(op.f('ix_employee_relations_attachments_case_id'), table_name='employee_relations_attachments')
    op.drop_table('employee_relations_attachments')
    # ### end Alembic commands ###
