"""Add last_updated to PIPRecord and created_at to TimelineEvent

Revision ID: e52626e7f497
Revises: a528a7276aa9
Create Date: 2025-07-20 22:11:57.959979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52626e7f497'
down_revision = 'a528a7276aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
