"""Add email to Employee

Revision ID: e6ba10759c18
Revises: f3fe6cc3d18b
Create Date: 2025-07-21 22:33:47.615995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ba10759c18'
down_revision = 'f3fe6cc3d18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'email')
    # ### end Alembic commands ###
