"""Add sickness case + meeting models

Revision ID: ea18fe6c0c6f
Revises: 879c66dddb8f
Create Date: 2026-02-15 16:53:56.077410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea18fe6c0c6f'
down_revision = '879c66dddb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
