"""Add status to PIPRecord

Revision ID: f2e144063f63
Revises: 
Create Date: 2025-07-20 22:06:21.453743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e144063f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('concerns',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('review_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('created_by')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('outcome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pip_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('review_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('concerns',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
