"""Add Employee Relations case and timeline models

Revision ID: f52141811ccb
Revises: ea18fe6c0c6f
Create Date: 2026-03-19 17:01:03.656040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52141811ccb'
down_revision = 'ea18fe6c0c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_relations_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('allegation_or_grievance', sa.Text(), nullable=False),
    sa.Column('date_raised', sa.Date(), nullable=False),
    sa.Column('raised_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('priority_level', sa.String(length=50), nullable=True),
    sa.Column('service_area', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('investigation_deadline', sa.Date(), nullable=True),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('outcome_due_date', sa.Date(), nullable=True),
    sa.Column('appeal_deadline', sa.Date(), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('outcome_status', sa.String(length=100), nullable=True),
    sa.Column('confidential_notes', sa.Text(), nullable=True),
    sa.Column('hr_lead', sa.String(length=120), nullable=True),
    sa.Column('investigating_manager', sa.String(length=120), nullable=True),
    sa.Column('hearing_chair', sa.String(length=120), nullable=True),
    sa.Column('note_taker', sa.String(length=120), nullable=True),
    sa.Column('appeal_manager', sa.String(length=120), nullable=True),
    sa.Column('disciplinary_category', sa.String(length=120), nullable=True),
    sa.Column('gross_misconduct_flag', sa.Boolean(), nullable=True),
    sa.Column('misconduct_date', sa.Date(), nullable=True),
    sa.Column('suspension_flag', sa.Boolean(), nullable=True),
    sa.Column('suspension_with_pay', sa.Boolean(), nullable=True),
    sa.Column('previous_warnings_summary', sa.Text(), nullable=True),
    sa.Column('recommended_sanction', sa.String(length=120), nullable=True),
    sa.Column('final_sanction', sa.String(length=120), nullable=True),
    sa.Column('warning_level', sa.String(length=120), nullable=True),
    sa.Column('warning_review_date', sa.Date(), nullable=True),
    sa.Column('warning_expiry_date', sa.Date(), nullable=True),
    sa.Column('grievance_category', sa.String(length=120), nullable=True),
    sa.Column('person_complained_about', sa.String(length=120), nullable=True),
    sa.Column('bullying_flag', sa.Boolean(), nullable=True),
    sa.Column('harassment_flag', sa.Boolean(), nullable=True),
    sa.Column('discrimination_flag', sa.Boolean(), nullable=True),
    sa.Column('requested_resolution', sa.Text(), nullable=True),
    sa.Column('mediation_considered', sa.Boolean(), nullable=True),
    sa.Column('grievance_outcome', sa.String(length=120), nullable=True),
    sa.Column('investigation_scope', sa.Text(), nullable=True),
    sa.Column('investigation_findings', sa.Text(), nullable=True),
    sa.Column('recommended_next_step', sa.Text(), nullable=True),
    sa.Column('appeal_requested_flag', sa.Boolean(), nullable=True),
    sa.Column('appeal_request_date', sa.Date(), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('appeal_hearing_date', sa.Date(), nullable=True),
    sa.Column('appeal_outcome', sa.String(length=120), nullable=True),
    sa.Column('appeal_outcome_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_cases_case_type'), 'employee_relations_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_employee_relations_cases_employee_id'), 'employee_relations_cases', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_cases_status'), 'employee_relations_cases', ['status'], unique=False)
    op.create_table('employee_relations_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_timeline_events_case_id'), 'employee_relations_timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_timeline_events_timestamp'), 'employee_relations_timeline_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_relations_timeline_events_timestamp'), table_name='employee_relations_timeline_events')
    op.drop_index(op.f('ix_employee_relations_timeline_events_case_id'), table_name='employee_relations_timeline_events')
    op.drop_table('employee_relations_timeline_events')
    op.drop_index(op.f('ix_employee_relations_cases_status'), table_name='employee_relations_cases')
    op.drop_index(op.f('ix_employee_relations_cases_employee_id'), table_name='employee_relations_cases')
    op.drop_index(op.f('ix_employee_relations_cases_case_type'), table_name='employee_relations_cases')
    op.drop_table('employee_relations_cases')
    # ### end Alembic commands ###
