"""Add employee relations ai advice

Revision ID: f774c8f8693c
Revises: 8d9e91746936
Create Date: 2026-03-23 22:21:42.023275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f774c8f8693c'
down_revision = '8d9e91746936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_relations_ai_advice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('policy_text_id', sa.Integer(), nullable=True),
    sa.Column('overall_risk_view', sa.Text(), nullable=True),
    sa.Column('immediate_next_steps', sa.Text(), nullable=True),
    sa.Column('investigation_questions', sa.Text(), nullable=True),
    sa.Column('hearing_questions', sa.Text(), nullable=True),
    sa.Column('outcome_sanction_guidance', sa.Text(), nullable=True),
    sa.Column('fairness_process_checks', sa.Text(), nullable=True),
    sa.Column('suggested_wording', sa.Text(), nullable=True),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.ForeignKeyConstraint(['policy_text_id'], ['employee_relations_policy_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_ai_advice_case_id'), 'employee_relations_ai_advice', ['case_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_ai_advice_created_at'), 'employee_relations_ai_advice', ['created_at'], unique=False)
    op.create_index(op.f('ix_employee_relations_ai_advice_policy_text_id'), 'employee_relations_ai_advice', ['policy_text_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_relations_ai_advice_policy_text_id'), table_name='employee_relations_ai_advice')
    op.drop_index(op.f('ix_employee_relations_ai_advice_created_at'), table_name='employee_relations_ai_advice')
    op.drop_index(op.f('ix_employee_relations_ai_advice_case_id'), table_name='employee_relations_ai_advice')
    op.drop_table('employee_relations_ai_advice')
    # ### end Alembic commands ###
